sudo: required 
services: 
    - docker 

before_install: 
    - docker build -t mkamau1/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true mkamau1/react-test npm test

after_success:
    - docker build -t mkamau1/multi-client ./client
    - docker build -t mkamau1/multi-nginx ./nginx
    - docker build -t mkamau1/multi-server ./server 
    - docker build -t mkamau1/multi-worker ./worker
    # Log in to the docker CLI 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take images and push them to docker hub 
    - docker push mkamau1/multi-client
    - docker push mkamau1/multi-nginx
    - docker push mkamau1/multi-server
    - docker push  mkamau1/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'eu-west-1'
    app: 'multi-docker'
    env: 'MultiDocker-env-1'
    bucket_name: 'elasticbeanstalk-eu-west-1-956163692607'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

